# Generated by Django 2.2 on 2019-07-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='study_field',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='study_field',
        ),
    ]
