# Generated by Django 2.2 on 2019-07-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20190716_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='university.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='university.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
