# Generated by Django 2.2 on 2019-07-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20190716_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_card',
            new_name='student_cards',
        ),
    ]
