# Generated by Django 2.2 on 2019-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20190716_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entrance',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_cards',
            field=models.ManyToManyField(blank=True, null=True, to='university.StudentCard'),
        ),
    ]
